networks:
  maryje_network:
    external: true

services:
  wordpress-init:
    image: wordpress:latest
    user: root
    volumes:
      - ${HOST_HOME}/maryje/wordpress:/var/www/html
    command: chown -R www-data:www-data /var/www/html

  wordpress:
    container_name: maryje_wordpress
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: maryje_db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: "define('FS_METHOD', 'direct');"
    volumes:
      - ${HOST_HOME}/maryje/wordpress:/var/www/html
    expose:
      - 80
    networks:
      - maryje_network
      - default
    depends_on:
      db:
        condition: service_started
      wordpress-init:
        condition: service_completed_successfully

  db:
    container_name: maryje_db
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${HOST_HOME}/maryje/db:/var/lib/mysql


